name: Run Tests

on:
  push:
    branches:
      - main # or the name of the branch you want to run tests on
  pull_request:
    branches:
      - main # or the name of the branch you want to run tests on

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x] # specify the Node.js versions you want to test against

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm test
